### PR TITLE
chore: replace from zisui to Storycap

### PR DESCRIPTION
**Pull request by Quramy**
*zisui* is already deprecated.

### CODE REVIEW

**Comment by nabeliwo** [comment]
Thank you for PR 🎉

storycap is failing with CI now.

image

The error message is `Error: Cannot find module 'puppeteer'`, but since there is `puppeteer` in yarn.lock, we are investigating the cause of fail.

**Comment by nabeliwo** [comment]
@Quramy 

Thank you for PR 🎉

storycap is failing with CI now.

image

The error message is `Error: Cannot find module 'puppeteer'`, but since there is `puppeteer` in yarn.lock, we are investigating the cause of fail.

**Comment by nabeliwo** [comment]
@Quramy The reason for failing with CI was running `npm install` instead of `yarn install`.

**Comment by Quramy** [comment]
> @Quramy The reason for failing with CI was running `npm install` instead of `yarn install`.

Oh, I got it!

Thanks for merge

**Pull request merged**
