### PR TITLE
Recreate kbn-zero as kbn-zero-re from the latest master

### PR DESCRIPTION
**Pull request by diescake**
## Related URL

none

## Overview

This branch is just for a review. DO NOT merge this !!

Now the `kbn-zero` branch which is forked from master has diverged. Unfortunately, we've squashed `master`'s modification and our customization, so we can't fast-foward and too hard to merge. :sob: 

## What I did

- Recreate `kbn-zero-re` from master and cherry-pick and squash some commits from kbn-zero.

## Capture

none

### CODE REVIEW

**Comment by diescake** [comment]
@ouji @moshisora 

Hi ! I try to organize `kbn-zero` branch to follow master.  Please let me know if you find some problems.

Thanks.

**Comment by ouji-miyahara** [comment]
僕の作業は全部入ってそうですー（ふんいき）

**Review by ouji-miyahara — APPROVED** [review]
たぶん LGTM

**Comment by diescake** [comment]
ARIGATOU for your review. Nanto naku eigo de PR tsukutta kedo nihongo de yoktta desune.

**Pull request merged**
