### PR TITLE
chore: replace from FC to VFC in `ThemeProvider`

### PR DESCRIPTION
**Pull request by wmoai**
## Related URL
https://smarthr.atlassian.net/browse/SHRUI-321

## Overview
Replace from `FC` to `VFC` in `ThemeProvider`

## What I did
- Replace to `VFC`.
- Change props of `ThemeProvider` simple.

### CODE REVIEW

**Comment by diescake** [comment]
@wmoai 
This PR is a WIP status, can I review it ? 🤔

**Comment by wmoai** [comment]
@diescake 
Yes, I've removed WIP !

**Review by diescake — APPROVED** [review]
That's nice !! LGTM !!

**Review by uknmr — APPROVED** [review]
LGTM:+1:

**Pull request merged**
