### PR TITLE
feat: add labelSuffix props to FieldSet component

### PR DESCRIPTION
**Pull request by nabeliwo**
## What I did

- add labelSuffix props
- add story of labelSuffix
- Style and description adjustment

## Capture

image

### CODE REVIEW

**Comment by nabeliwo** [comment]
@diescake Please review 🙏

**Comment by diescake** [comment]
You got it ! I'll check in soon. 🎉

**Comment by diescake** [comment]
I have a little concern about regressions of the layout.

https://smarthr-ui-snapshots.s3.amazonaws.com/901a50cf2aad31467583b9a6a79dbe6dd68f23e3/index.html?stat=q1ZKS8zMSU3xLEnNLXbOL80rUbIy1FHKSy1HFjHQUUpJzUktQVUHFC1ILC5GFTQ1rQUA

According to the above Diff, the components that the `labelSuffix` is not specified are also affected of layout.

Concretely, the `display: flex` in the `Title` component affects that, but I have no good idea to solve that problem. 🤔

**Comment by nabeliwo** [comment]
@diescake I think that it is the correct behavior that affects components that do not have `labelSuffix` specified.

Because the existing `Title` was a wrong style that didn't center vertically.

before

image

after

image

I think that with this fix, it also improved together.

I'm thinking of posting this in the CHANGELOG, but should it be separated into a separate pull request?

**Comment by diescake** [comment]
@nabeliwo 

> @diescake I think that it is the correct behavior that affects components that do not have `labelSuffix` specified.
> 
> Because the existing `Title` was a wrong style that didn't center vertically.

That makes sense. Thanks for your detailed reply. 👍 

>I'm thinking of posting this in the CHANGELOG, but should it be separated into a separate pull request?

Great !! I feel we don't have to separate pull request.

**Pull request merged**
